### ISSUE TITLE
Demo Web Panel Link

### ISSUE THREAD

**Issue by xe1os** [csgo-league/csgo-league-web#35]
@b3none kudos!! appreciate your work on this project. Would love to see the demo of this web panel

https://league.voidrealitygaming.co.uk link doesnt work it redirects to your personal website.

Thank you :)

**Comment by B3none** [comment]
Hey man, yeah sorry about this! It redirects to my personal site because I didn’t have time to continue the initial project. I’ll look at getting some screenshots added if I can find the time 🙂

**Comment by xe1os** [comment]
@b3none can you share us the panel link? would like to see the functionalities your panel has and would also like to share ideas.

**Comment by B3none** [comment]
Hey Xe1os, I'll look at getting one up I just struggle for time and data! :P If you'd like to provide some I can definitely put it live. It's been a while since I was running this setup locally so it'd be nice to get it all rolling. As far as I am aware there are quite a few bugs in the way but as I can see interest is spiking it would be nice to iron them all out and get a real stable version of this project released!

-- Thanks for your extended patience and contributions to the project.

**Comment by B3none** [comment]
I have now setup - https://github.com/csgo-league/examples
